name: starrotator-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - astropy
  - matplotlib
  - numpy
  - requests
  - pytest
  - pytest-cov
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-rtd-theme
  - jax[cpu]
  - pip
  - pip:
      - pysme-astro
      - jaxoplanet